-timescale=1ns/1ps
+incdir+common
+incdir+new_version
./new_version/pbit_pkg.sv
./common/dff_sets.sv
./new_version/UART_RX.sv
./new_version/UART_TX.sv
./new_version/pbit_uart_reg_master.sv
./tb/uart_rx/tb_uart_byte_timeout.sv
