+incdir+common
+incdir+new_version
+incdir+tb
./common/dff_sets.sv
./new_version/pbit_pkg.sv
./new_version/pbit_edge_contrib2.sv
./new_version/majority_vote.sv
./new_version/pbit_prob_compare16.sv
./new_version/pbit_rand16_extract.sv
./new_version/comparator_vote.sv
./new_version/tanh_LUT.sv
./new_version/pbit_8edge_compute.sv
./new_version/edge_prob_compare.sv
./new_version/edge_compare8_named.sv
./new_version/mac.sv
./new_version/lfsr32_rng32.sv
./new_version/pbit_control.sv
./new_version/UART_RX.sv
./new_version/UART_TX.sv
./new_version/edge_reg_coupler.sv
./new_version/pbit_node.sv
./new_version/pbit_reg_block.sv
./new_version/pbit_uart_reg_master.sv
./new_version/phase_control_4color.sv
./new_version/pbit_array_kings.sv
./new_version/pbit_uart_reg_subsystem.sv
./new_version/pbit_top.sv
./tb/tb_run_3x3_majority.sv
