`timescale 1ns/1ps

module tb_gate_pipeline_suite;
    localparam logic [15:0] A_GLOBAL_CTRL     = 16'h0000;
    localparam logic [15:0] A_GLOBAL_CFG      = 16'h0004;
    localparam logic [15:0] A_GLOBAL_STATUS   = 16'h0008;
    localparam logic [15:0] A_ERROR_STATUS    = 16'h000c;
    localparam logic [15:0] A_SNAPSHOT_ADDR   = 16'h0010;
    localparam logic [15:0] A_I0_LEVEL0       = 16'h0014;
    localparam logic [15:0] A_SWEEP_INTERVAL0 = 16'h0034;
    localparam logic [15:0] A_UNIT_TARGET     = 16'h0074;
    localparam logic [15:0] A_NODE_TARGET     = 16'h0078;
    localparam logic [15:0] A_NODE_CFG        = 16'h007c;
    localparam logic [15:0] A_NODE_CMD        = 16'h0080;
    localparam logic [15:0] A_NODE_RDATA_CFG  = 16'h0084;
    localparam logic [15:0] A_SEED_TARGET     = 16'h0088;
    localparam logic [15:0] A_SEED            = 16'h008c;
    localparam logic [15:0] A_SEED_CMD        = 16'h0090;
    localparam logic [15:0] A_SEED_RDATA      = 16'h0094;
    localparam logic [15:0] A_EDGE_TARGET     = 16'h0098;
    localparam logic [15:0] A_EDGE_CFG        = 16'h009c;
    localparam logic [15:0] A_EDGE_CMD        = 16'h00a0;
    localparam logic [15:0] A_EDGE_RDATA      = 16'h00a4;
    localparam logic [15:0] A_SPIN_RDATA0     = 16'h00a8;

    localparam int CFG_DONE_SET_BIT   = 0;
    localparam int RUN_START_BIT      = 2;
    localparam int SNAPSHOT_LATCH_BIT = 3;
    localparam int RUN_DONE_CLEAR_BIT = 4;
    localparam int CFG_DONE_BIT       = 0;
    localparam int RUN_BUSY_BIT       = 1;
    localparam int RUN_DONE_BIT       = 2;
    localparam int SNAPSHOT_VALID_BIT = 5;
    localparam int ERROR_BIT          = 6;

    localparam int ROWS = 20;
    localparam int COLS = 20;
    localparam int NODE_IN_UNIT = 8;
    localparam int N_SPIN = 3200;
    localparam int SNAPSHOT_WIDTH = 320;
    localparam int SNAPSHOT_PAGES = 10;
    localparam int WORDS_PER_PAGE = 10;

    gate_pipeline_env env();
    logic [N_SPIN-1:0] snapshot_first = '0;
    logic [N_SPIN-1:0] snapshot_second = '0;
    logic [15:0] pll_cfg;
    string test_name;

`ifdef GATE_SDF
    // Generated by run_gate_pipeline_500_sdf_sbatch.sh. VCS 2018 requires
    // the SDF filename to be a compile-time string literal.
    `include "gate_sdf_setup.svh"
`endif

    task automatic capture_word0(output logic [31:0] snapshot_word);
        logic [31:0] status;
        env.core_write(A_SNAPSHOT_ADDR, 32'd0);
        env.core_write(A_GLOBAL_CTRL, 32'(1 << SNAPSHOT_LATCH_BIT));
        env.core_read(A_GLOBAL_STATUS, status);
        if (!status[SNAPSHOT_VALID_BIT] || status[ERROR_BIT])
            $fatal(1, "Snapshot status invalid: %h", status);
        env.core_read(A_SPIN_RDATA0, snapshot_word);
    endtask

    task automatic run_basic;
        env.core_write(A_GLOBAL_CFG, 32'h0400_0001);
        env.core_read_check(A_GLOBAL_CFG, 32'h0400_0001);
        env.core_read_check(A_ERROR_STATUS, 32'd0);
        $display("[TB_GATE_PIPELINE_BASIC] PASS pll_cfg=0x%04h transactions=%0d",
                 pll_cfg, env.core_transactions);
    endtask

    task automatic run_small;
        logic [31:0] status;
        logic [31:0] before_spins;
        logic [31:0] after_spins;

        // One sweep, majority five, with maximum I0 for deterministic MaxCut.
        env.core_write(A_GLOBAL_CFG, 32'h0400_0000);
        env.core_read_check(A_GLOBAL_CFG, 32'h0400_0000);
        env.core_write(A_I0_LEVEL0, 32'h1f1f_1f1f);
        env.core_write(A_SWEEP_INTERVAL0, 32'd0);

        env.core_write(A_UNIT_TARGET, 32'd0);
        // Node 0 is clamped high.
        env.core_write(A_NODE_TARGET, 32'h0000_0000);
        env.core_write(A_NODE_CFG, 32'h0000_0703);
        env.core_write(A_NODE_CMD, 32'h0000_0003);
        env.core_read_check(A_NODE_RDATA_CFG, 32'h0000_0007);
        // Node 4 starts high and is free to move.
        env.core_write(A_NODE_TARGET, 32'h0000_0100);
        env.core_write(A_NODE_CFG, 32'h0000_0101);
        env.core_write(A_NODE_CMD, 32'h0000_0003);
        env.core_read_check(A_NODE_RDATA_CFG, 32'h0000_0001);

        env.core_write(A_SEED_TARGET, 32'd0);
        env.core_write(A_SEED, 32'h1357_9bdf);
        env.core_write(A_SEED_CMD, 32'h0000_0003);
        env.core_read_check(A_SEED_RDATA, 32'h1357_9bdf);

        // Edge type 0/number 0 joins node 0 and node 4. J=-1, p=127.
        env.core_write(A_EDGE_TARGET, 32'h0000_0000);
        env.core_write(A_EDGE_CFG, 32'h0000_01fd);
        env.core_write(A_EDGE_CMD, 32'h0000_0005);
        env.core_read_check(A_EDGE_RDATA, 32'h0000_01fd);
        env.core_read_check(A_ERROR_STATUS, 32'd0);

        capture_word0(before_spins);
        if (before_spins[0] !== 1'b1 || before_spins[4] !== 1'b1)
            $fatal(1, "Wrong initial small-problem state: %h", before_spins);

        env.core_write(A_GLOBAL_CTRL, 32'(1 << CFG_DONE_SET_BIT));
        env.core_write(A_GLOBAL_CTRL, 32'(1 << RUN_START_BIT));
        env.core_read(A_GLOBAL_STATUS, status);
        if (!status[CFG_DONE_BIT] || !status[RUN_DONE_BIT] ||
            status[RUN_BUSY_BIT] || status[ERROR_BIT])
            $fatal(1, "Unexpected small-problem status=%h", status);

        capture_word0(after_spins);
        if (after_spins[0] !== 1'b1 || after_spins[4] !== 1'b0)
            $fatal(1, "Two-node MaxCut failed before=%h after=%h",
                   before_spins, after_spins);
        env.core_write(A_GLOBAL_CTRL, 32'(1 << RUN_DONE_CLEAR_BIT));
        env.core_read_check(A_ERROR_STATUS, 32'd0);
        $display("[TB_GATE_PIPELINE_SMALL] PASS problem=two_node_maxcut transactions=%0d",
                 env.core_transactions);
    endtask

    task automatic configure_marker(input integer flat_index);
        integer unit_index;
        integer unit_row;
        integer unit_col;
        integer node_number;
        begin
            unit_index = flat_index / NODE_IN_UNIT;
            unit_row = unit_index / COLS;
            unit_col = unit_index % COLS;
            node_number = flat_index % NODE_IN_UNIT;
            env.core_write(A_UNIT_TARGET,
                           unit_row | (unit_col << 8));
            env.core_write(A_NODE_TARGET,
                           (node_number & 3) | ((node_number >> 2) << 8));
            env.core_write(A_NODE_CFG, 32'h0000_0703);
            env.core_write(A_NODE_CMD, 32'h0000_0001);
        end
    endtask

    task automatic capture_all(input integer pass_number);
        logic [31:0] status;
        logic [31:0] word_value;
        integer page;
        integer word_idx;
        integer base;
        begin
            for (page = 0; page < SNAPSHOT_PAGES; page++) begin
                env.core_write(A_SNAPSHOT_ADDR, page);
                env.core_write(A_GLOBAL_CTRL,
                               32'(1 << SNAPSHOT_LATCH_BIT));
                env.core_read(A_GLOBAL_STATUS, status);
                if (!status[CFG_DONE_BIT] || !status[RUN_DONE_BIT] ||
                    status[RUN_BUSY_BIT] || !status[SNAPSHOT_VALID_BIT] ||
                    status[ERROR_BIT])
                    $fatal(1, "Snapshot pass=%0d page=%0d status=%h",
                           pass_number, page, status);
                for (word_idx = 0; word_idx < WORDS_PER_PAGE; word_idx++) begin
                    env.core_read(A_SPIN_RDATA0 + 4*word_idx, word_value);
                    if (^word_value === 1'bx)
                        $fatal(1, "X in snapshot pass=%0d page=%0d word=%0d value=%h",
                               pass_number, page, word_idx, word_value);
                    base = page*SNAPSHOT_WIDTH + word_idx*32;
                    if (pass_number == 1)
                        snapshot_first[base +: 32] = word_value;
                    else
                        snapshot_second[base +: 32] = word_value;
                end
                $display("[GATE_LARGE] snapshot pass=%0d page=%0d/%0d PASS",
                         pass_number, page+1, SNAPSHOT_PAGES);
            end
        end
    endtask

    task automatic run_large;
        logic [31:0] status;
        logic [31:0] errors;
        integer page;
        integer marker_a;
        integer marker_b;

        // Two distinct clamped-high markers per page. Their word and bit
        // positions vary with the page, exposing page/word/bit address errors.
        for (page = 0; page < SNAPSHOT_PAGES; page++) begin
            marker_a = page*SNAPSHOT_WIDTH + page*32 + page;
            marker_b = page*SNAPSHOT_WIDTH + (9-page)*32 + (31-page);
            configure_marker(marker_a);
            configure_marker(marker_b);
        end

        env.core_write(A_GLOBAL_CFG, 32'd0); // one sweep, majority one
        env.core_write(A_GLOBAL_CTRL, 32'(1 << CFG_DONE_SET_BIT));
        env.core_write(A_GLOBAL_CTRL, 32'(1 << RUN_START_BIT));
        env.core_read(A_GLOBAL_STATUS, status);
        if (!status[CFG_DONE_BIT] || !status[RUN_DONE_BIT] ||
            status[RUN_BUSY_BIT] || status[ERROR_BIT])
            $fatal(1, "Unexpected large-test run status=%h", status);

        capture_all(1);
        #10us;
        capture_all(2);
        if (snapshot_first !== snapshot_second)
            $fatal(1, "3200-bit state changed after RUN_DONE");

        for (page = 0; page < SNAPSHOT_PAGES; page++) begin
            marker_a = page*SNAPSHOT_WIDTH + page*32 + page;
            marker_b = page*SNAPSHOT_WIDTH + (9-page)*32 + (31-page);
            if (snapshot_first[marker_a] !== 1'b1 ||
                snapshot_first[marker_b] !== 1'b1)
                $fatal(1, "Marker mismatch page=%0d a=%0d:%b b=%0d:%b",
                       page, marker_a, snapshot_first[marker_a],
                       marker_b, snapshot_first[marker_b]);
        end
        env.core_read(A_ERROR_STATUS, errors);
        if (errors !== 32'd0)
            $fatal(1, "Large snapshot test errors=%h", errors);
        $display("[TB_GATE_PIPELINE_LARGE] PASS bits=3200 pages=10 words=100 markers=20 transactions=%0d",
                 env.core_transactions);
    endtask

    initial begin : TEST
        test_name = "basic";
        pll_cfg = 16'h0228; // REF=25MHz, N=40, OD=1 -> 500MHz.
        void'($value$plusargs("TEST=%s", test_name));
        void'($value$plusargs("PLL_CFG=%h", pll_cfg));
        $display("[GATE_SUITE] test=%s pll_cfg=0x%04h", test_name, pll_cfg);
        env.initialize(pll_cfg);
        case (test_name)
            "basic": run_basic();
            "small": run_small();
            "large": run_large();
            default: $fatal(1, "TEST must be basic, small or large: %s",
                            test_name);
        endcase
        $finish;
    end

    initial begin
        #200ms;
        $fatal(1, "TB_GATE_PIPELINE_SUITE timeout test=%s transactions=%0d",
               test_name, env.core_transactions);
    end
endmodule
