`ifndef PBIT_PKG
`define PBIT_PKG
package pbit_pkg;
    //array parameters
    parameter int ROWS = 40;
    parameter int COLS = 40;
    parameter int SHARED_ROWS = (ROWS+1)/2;
    parameter int SHARED_COLS = (COLS+1)/2;
    // SCALED_STRUCT_SYNC: Derive regional banks while preserving the current 40x40 configuration.
    parameter int TANH_BANK_TILE_ROWS = 10;
    parameter int TANH_BANK_TILE_COLS = 10;
    parameter int TANH_BANK_ROWS = (SHARED_ROWS + TANH_BANK_TILE_ROWS - 1) / TANH_BANK_TILE_ROWS;
    parameter int TANH_BANK_COLS = (SHARED_COLS + TANH_BANK_TILE_COLS - 1) / TANH_BANK_TILE_COLS;
    parameter int TANH_BANK_NUM = TANH_BANK_ROWS * TANH_BANK_COLS;
    parameter int REF_CLK_FREQ_HZ = 25_000_000;
    parameter int CLK_FREQ_HZ = 400_000_000;
    parameter int BAUD_RATE = 10_000_000;
    parameter int N_SPIN = ROWS * COLS;
    parameter int SNAPSHOT_WIDTH = 320;
    parameter int SPIN_RDATA_REG_NUM = SNAPSHOT_WIDTH / 32;
    // SCALED_STRUCT_SYNC: Round up snapshot pages; the current 1600 spins still occupy five pages.
    parameter int SPIN_ADDR_MAX = (N_SPIN + SNAPSHOT_WIDTH - 1) / SNAPSHOT_WIDTH;
    parameter int I0_LEVEL_WIDTH = 6;
    parameter int SWEEP_INTERVAL_WIDTH = 16;
    parameter int NUM_MAJORITY_MAX = 32;
    parameter int MACSUM_WIDTH = 5;
    parameter int LUT_WIDTH = 16;
    parameter int PBIT_8EDGE_COMPUTE_WIDTH = 5;
    parameter int SWEEP_ROUND_NUM = 64;
    parameter int SWEEP_ROUND_WIDTH = $clog2(SWEEP_ROUND_NUM);
    //Node target reg
    // Node target reg
    parameter logic [15:0] A_NODE_TARGET = 16'h00D8;
    parameter TARGET_MODE_WIDTH = 2;
    parameter logic [TARGET_MODE_WIDTH-1:0] TARGET_MODE_GLOBAL = 2'd0;
    parameter logic [TARGET_MODE_WIDTH-1:0] TARGET_MODE_ROW = 2'd1;
    parameter logic [TARGET_MODE_WIDTH-1:0] TARGET_MODE_LOCAL = 2'd2;
    parameter TARGET_MODE_LSB = 0;
    parameter TARGET_MODE_MSB = TARGET_MODE_LSB + TARGET_MODE_WIDTH - 1;
    parameter NODE_TARGET_ROW_WIDTH = $clog2(ROWS);
    parameter NODE_TARGET_ROW_LSB = 8;
    parameter NODE_TARGET_ROW_MSB = NODE_TARGET_ROW_LSB + NODE_TARGET_ROW_WIDTH - 1;
    parameter NODE_TARGET_COL_WIDTH = $clog2(COLS);
    parameter NODE_TARGET_COL_LSB = 16;
    parameter NODE_TARGET_COL_MSB = NODE_TARGET_COL_LSB + NODE_TARGET_COL_WIDTH - 1;

    parameter NODE_TARGET_PACKED_WIDTH = TARGET_MODE_WIDTH + NODE_TARGET_ROW_WIDTH + NODE_TARGET_COL_WIDTH;
    parameter TARGET_MODE_PACKED_LSB = 0;
    parameter TARGET_MODE_PACKED_MSB = TARGET_MODE_PACKED_LSB + TARGET_MODE_WIDTH - 1;
    parameter NODE_TARGET_ROW_PACKED_LSB = TARGET_MODE_PACKED_MSB + 1;
    parameter NODE_TARGET_ROW_PACKED_MSB = NODE_TARGET_ROW_PACKED_LSB + NODE_TARGET_ROW_WIDTH - 1;
    parameter NODE_TARGET_COL_PACKED_LSB = NODE_TARGET_ROW_PACKED_MSB + 1;
    parameter NODE_TARGET_COL_PACKED_MSB = NODE_TARGET_COL_PACKED_LSB + NODE_TARGET_COL_WIDTH - 1;

    // Node cfg reg
    parameter logic [15:0] A_NODE_CFG = 16'h00DC;
    parameter INIT_VALID_WIDTH = 1;
    parameter INIT_VALID_LSB = 0;
    parameter INIT_VALID_MSB = INIT_VALID_LSB + INIT_VALID_WIDTH - 1;
    parameter CLAMP_VALID_WIDTH = 1;
    parameter CLAMP_VALID_LSB = 1;
    parameter CLAMP_VALID_MSB = CLAMP_VALID_LSB + CLAMP_VALID_WIDTH - 1;
    parameter BIAS_VALID_WIDTH = 1;
    parameter BIAS_VALID_LSB = 2;
    parameter BIAS_VALID_MSB = BIAS_VALID_LSB + BIAS_VALID_WIDTH - 1;
    parameter NODE_CFG_INIT_SPIN_WIDTH = 1;
    parameter NODE_CFG_INIT_SPIN_LSB = 8;
    parameter NODE_CFG_INIT_SPIN_MSB = NODE_CFG_INIT_SPIN_LSB + NODE_CFG_INIT_SPIN_WIDTH - 1;
    parameter NODE_CFG_CLAMP_EN_WIDTH = 1;
    parameter NODE_CFG_CLAMP_EN_LSB = 9;
    parameter NODE_CFG_CLAMP_EN_MSB = NODE_CFG_CLAMP_EN_LSB + NODE_CFG_CLAMP_EN_WIDTH - 1;
    parameter NODE_CFG_CLAMP_SPIN_WIDTH = 1;
    parameter NODE_CFG_CLAMP_SPIN_LSB = 10;
    parameter NODE_CFG_CLAMP_SPIN_MSB = NODE_CFG_CLAMP_SPIN_LSB + NODE_CFG_CLAMP_SPIN_WIDTH - 1;
    parameter NODE_CFG_BIAS_SIGN_WIDTH = 1;
    parameter NODE_CFG_BIAS_SIGN_LSB = 11;
    parameter NODE_CFG_BIAS_SIGN_MSB = NODE_CFG_BIAS_SIGN_LSB + NODE_CFG_BIAS_SIGN_WIDTH - 1;
    parameter NODE_CFG_BIAS_PROB_WIDTH = 7;
    parameter NODE_CFG_BIAS_PROB_LSB = 12;
    parameter NODE_CFG_BIAS_PROB_MSB = NODE_CFG_BIAS_PROB_LSB + NODE_CFG_BIAS_PROB_WIDTH - 1;

    parameter NODE_CFG_W = NODE_CFG_INIT_SPIN_WIDTH + NODE_CFG_CLAMP_EN_WIDTH + NODE_CFG_CLAMP_SPIN_WIDTH + NODE_CFG_BIAS_SIGN_WIDTH + NODE_CFG_BIAS_PROB_WIDTH;
    parameter NODE_CFG_VALID_W = INIT_VALID_WIDTH + CLAMP_VALID_WIDTH + BIAS_VALID_WIDTH;
    parameter NODE_CFG_PACKED_WIDTH = NODE_CFG_VALID_W + NODE_CFG_W;
    parameter INIT_VALID_PACKED_LSB = 0;
    parameter INIT_VALID_PACKED_MSB = INIT_VALID_PACKED_LSB + INIT_VALID_WIDTH - 1;
    parameter CLAMP_VALID_PACKED_LSB = INIT_VALID_PACKED_MSB + 1;
    parameter CLAMP_VALID_PACKED_MSB = CLAMP_VALID_PACKED_LSB + CLAMP_VALID_WIDTH - 1;
    parameter BIAS_VALID_PACKED_LSB = CLAMP_VALID_PACKED_MSB + 1;
    parameter BIAS_VALID_PACKED_MSB = BIAS_VALID_PACKED_LSB + BIAS_VALID_WIDTH - 1;
    parameter NODE_CFG_INIT_SPIN_PACKED_LSB = BIAS_VALID_PACKED_MSB + 1;
    parameter NODE_CFG_INIT_SPIN_PACKED_MSB = NODE_CFG_INIT_SPIN_PACKED_LSB + NODE_CFG_INIT_SPIN_WIDTH - 1;
    parameter NODE_CFG_CLAMP_EN_PACKED_LSB = NODE_CFG_INIT_SPIN_PACKED_MSB + 1;
    parameter NODE_CFG_CLAMP_EN_PACKED_MSB = NODE_CFG_CLAMP_EN_PACKED_LSB + NODE_CFG_CLAMP_EN_WIDTH - 1;
    parameter NODE_CFG_CLAMP_SPIN_PACKED_LSB = NODE_CFG_CLAMP_EN_PACKED_MSB + 1;
    parameter NODE_CFG_CLAMP_SPIN_PACKED_MSB = NODE_CFG_CLAMP_SPIN_PACKED_LSB + NODE_CFG_CLAMP_SPIN_WIDTH - 1;
    parameter NODE_CFG_BIAS_SIGN_PACKED_LSB = NODE_CFG_CLAMP_SPIN_PACKED_MSB + 1;
    parameter NODE_CFG_BIAS_SIGN_PACKED_MSB = NODE_CFG_BIAS_SIGN_PACKED_LSB + NODE_CFG_BIAS_SIGN_WIDTH - 1;
    parameter NODE_CFG_BIAS_PROB_PACKED_LSB = NODE_CFG_BIAS_SIGN_PACKED_MSB + 1;
    parameter NODE_CFG_BIAS_PROB_PACKED_MSB = NODE_CFG_BIAS_PROB_PACKED_LSB + NODE_CFG_BIAS_PROB_WIDTH - 1;

    // Node seed reg
    parameter logic [15:0] A_NODE_SEED = 16'h00E0;
    parameter NODE_SEED_WIDTH = 32;
    parameter NODE_SEED_LSB = 0;
    parameter NODE_SEED_MSB = NODE_SEED_LSB + NODE_SEED_WIDTH - 1;
    parameter NODE_SEED_PACKED_WIDTH = NODE_SEED_WIDTH;
    parameter NODE_SEED_PACKED_LSB = 0;
    parameter NODE_SEED_PACKED_MSB = NODE_SEED_PACKED_LSB + NODE_SEED_WIDTH - 1;

    // Edge target reg
    parameter logic [15:0] A_EDGE_TARGET = 16'h00F0;
    parameter EDGE_TYPE_WIDTH = 2;
    parameter EDGE_TYPE_EDGE_H = 2'd0;
    parameter EDGE_TYPE_EDGE_V = 2'd1;
    parameter EDGE_TYPE_EDGE_DSE = 2'd2;
    parameter EDGE_TYPE_EDGE_DSW = 2'd3;
    parameter EDGE_TYPE_LSB = 0;
    parameter EDGE_TYPE_MSB = EDGE_TYPE_LSB + EDGE_TYPE_WIDTH - 1;
    parameter EDGE_TARGET_ROW_WIDTH = $clog2(ROWS);
    parameter EDGE_TARGET_ROW_LSB = 8;
    parameter EDGE_TARGET_ROW_MSB = EDGE_TARGET_ROW_LSB + EDGE_TARGET_ROW_WIDTH - 1;
    parameter EDGE_TARGET_COL_WIDTH = $clog2(COLS);
    parameter EDGE_TARGET_COL_LSB = 16;
    parameter EDGE_TARGET_COL_MSB = EDGE_TARGET_COL_LSB + EDGE_TARGET_COL_WIDTH - 1;

    parameter EDGE_TARGET_PACKED_WIDTH = EDGE_TYPE_WIDTH + EDGE_TARGET_ROW_WIDTH + EDGE_TARGET_COL_WIDTH;
    parameter EDGE_TYPE_PACKED_LSB = 0;
    parameter EDGE_TYPE_PACKED_MSB = EDGE_TYPE_PACKED_LSB + EDGE_TYPE_WIDTH - 1;
    parameter EDGE_TARGET_ROW_PACKED_LSB = EDGE_TYPE_PACKED_MSB + 1;
    parameter EDGE_TARGET_ROW_PACKED_MSB = EDGE_TARGET_ROW_PACKED_LSB + EDGE_TARGET_ROW_WIDTH - 1;
    parameter EDGE_TARGET_COL_PACKED_LSB = EDGE_TARGET_ROW_PACKED_MSB + 1;
    parameter EDGE_TARGET_COL_PACKED_MSB = EDGE_TARGET_COL_PACKED_LSB + EDGE_TARGET_COL_WIDTH - 1;
    
    // Edge cfg reg
    parameter logic [15:0] A_EDGE_CFG = 16'h00F4;
    parameter EDGE_CFG_EDGE_VALID_WIDTH = 1;
    parameter EDGE_CFG_EDGE_VALID_LSB = 0;
    parameter EDGE_CFG_EDGE_VALID_MSB = EDGE_CFG_EDGE_VALID_LSB + EDGE_CFG_EDGE_VALID_WIDTH - 1;
    parameter EDGE_CFG_EDGE_SIGN_WIDTH = 1;
    parameter EDGE_CFG_EDGE_SIGN_LSB = 1;
    parameter EDGE_CFG_EDGE_SIGN_MSB = EDGE_CFG_EDGE_SIGN_LSB + EDGE_CFG_EDGE_SIGN_WIDTH - 1;
    parameter EDGE_CFG_EDGE_PROB_WIDTH = 7;
    parameter EDGE_CFG_EDGE_PROB_LSB = 2;
    parameter EDGE_CFG_EDGE_PROB_MSB = EDGE_CFG_EDGE_PROB_LSB + EDGE_CFG_EDGE_PROB_WIDTH - 1;

    parameter EDGE_CFG_PACKED_WIDTH = EDGE_CFG_EDGE_VALID_WIDTH + EDGE_CFG_EDGE_SIGN_WIDTH + EDGE_CFG_EDGE_PROB_WIDTH;
    parameter EDGE_CFG_EDGE_VALID_PACKED_LSB = 0;
    parameter EDGE_CFG_EDGE_VALID_PACKED_MSB = EDGE_CFG_EDGE_VALID_PACKED_LSB + EDGE_CFG_EDGE_VALID_WIDTH - 1;
    parameter EDGE_CFG_EDGE_SIGN_PACKED_LSB = EDGE_CFG_EDGE_VALID_PACKED_MSB + 1;
    parameter EDGE_CFG_EDGE_SIGN_PACKED_MSB = EDGE_CFG_EDGE_SIGN_PACKED_LSB + EDGE_CFG_EDGE_SIGN_WIDTH - 1;
    parameter EDGE_CFG_EDGE_PROB_PACKED_LSB = EDGE_CFG_EDGE_SIGN_PACKED_MSB + 1;
    parameter EDGE_CFG_EDGE_PROB_PACKED_MSB = EDGE_CFG_EDGE_PROB_PACKED_LSB + EDGE_CFG_EDGE_PROB_WIDTH - 1;

    // Snapshot addr reg
    parameter logic [15:0] A_SNAPSHOT_ADDR = 16'h0014;
    // SCALED_STRUCT_SYNC: Derive page address width; the current configuration still uses three bits.
    parameter SNAPSHOT_ADDR_WIDTH = (SPIN_ADDR_MAX <= 1) ? 1 : $clog2(SPIN_ADDR_MAX);
    parameter SNAPSHOT_ADDR_LSB = 0;
    parameter SNAPSHOT_ADDR_MSB = SNAPSHOT_ADDR_LSB + SNAPSHOT_ADDR_WIDTH - 1;

    parameter SNAPSHOT_ADDR_PACKED_WIDTH = SNAPSHOT_ADDR_WIDTH;
    parameter SNAPSHOT_ADDR_PACKED_LSB = 0;
    parameter SNAPSHOT_ADDR_PACKED_MSB = SNAPSHOT_ADDR_PACKED_LSB + SNAPSHOT_ADDR_WIDTH - 1;

    parameter I0_LEVEL_REG_NUM = SWEEP_ROUND_NUM / 4;
    // I0 level0 reg
    parameter logic [15:0] A_I0_LEVEL0 = 16'h0018;
    // I0 level1 reg
    parameter logic [15:0] A_I0_LEVEL1 = 16'h001C;
    // I0 level2 reg
    parameter logic [15:0] A_I0_LEVEL2 = 16'h0020;
    // I0 level3 reg
    parameter logic [15:0] A_I0_LEVEL3 = 16'h0024;
    // I0 level4 reg
    parameter logic [15:0] A_I0_LEVEL4 = 16'h0028;
    // I0 level5 reg
    parameter logic [15:0] A_I0_LEVEL5 = 16'h002C;
    // I0 level6 reg
    parameter logic [15:0] A_I0_LEVEL6 = 16'h0030;
    // I0 level7 reg
    parameter logic [15:0] A_I0_LEVEL7 = 16'h0034;
    // I0 level8 reg
    parameter logic [15:0] A_I0_LEVEL8 = 16'h0038;
    // I0 level9 reg
    parameter logic [15:0] A_I0_LEVEL9 = 16'h003C;
    // I0 level10 reg
    parameter logic [15:0] A_I0_LEVEL10 = 16'h0040;
    // I0 level11 reg
    parameter logic [15:0] A_I0_LEVEL11 = 16'h0044;
    // I0 level12 reg
    parameter logic [15:0] A_I0_LEVEL12 = 16'h0048;
    // I0 level13 reg
    parameter logic [15:0] A_I0_LEVEL13 = 16'h004C;
    // I0 level14 reg
    parameter logic [15:0] A_I0_LEVEL14 = 16'h0050;
    // I0 level15 reg
    parameter logic [15:0] A_I0_LEVEL15 = 16'h0054;
    
    parameter I0_LEVEL0_WIDTH = 6;
    parameter I0_LEVEL0_LSB = 0;
    parameter I0_LEVEL0_MSB = I0_LEVEL0_LSB + I0_LEVEL0_WIDTH - 1;
    parameter I0_LEVEL1_WIDTH = 6;
    parameter I0_LEVEL1_LSB = 8;
    parameter I0_LEVEL1_MSB = I0_LEVEL1_LSB + I0_LEVEL1_WIDTH - 1;
    parameter I0_LEVEL2_WIDTH = 6;
    parameter I0_LEVEL2_LSB = 16;
    parameter I0_LEVEL2_MSB = I0_LEVEL2_LSB + I0_LEVEL2_WIDTH - 1;
    parameter I0_LEVEL3_WIDTH = 6;
    parameter I0_LEVEL3_LSB = 24;
    parameter I0_LEVEL3_MSB = I0_LEVEL3_LSB + I0_LEVEL3_WIDTH - 1;
    parameter I0_LEVEL_PACKED_WIDTH = I0_LEVEL0_WIDTH + I0_LEVEL1_WIDTH + I0_LEVEL2_WIDTH + I0_LEVEL3_WIDTH;
    parameter I0_LEVEL0_PACKED_LSB = 0;
    parameter I0_LEVEL0_PACKED_MSB = I0_LEVEL0_PACKED_LSB + I0_LEVEL0_WIDTH - 1;
    parameter I0_LEVEL1_PACKED_LSB = I0_LEVEL0_PACKED_MSB + 1;
    parameter I0_LEVEL1_PACKED_MSB = I0_LEVEL1_PACKED_LSB + I0_LEVEL1_WIDTH - 1;
    parameter I0_LEVEL2_PACKED_LSB = I0_LEVEL1_PACKED_MSB + 1;
    parameter I0_LEVEL2_PACKED_MSB = I0_LEVEL2_PACKED_LSB + I0_LEVEL2_WIDTH - 1;
    parameter I0_LEVEL3_PACKED_LSB = I0_LEVEL2_PACKED_MSB + 1;
    parameter I0_LEVEL3_PACKED_MSB = I0_LEVEL3_PACKED_LSB + I0_LEVEL3_WIDTH - 1;

    parameter int SWEEP_INTERVAL_REG_NUM = SWEEP_ROUND_NUM / 2;
    // Sweep interval0 reg
    parameter logic [15:0] A_SWEEP_INTERVAL0 = 16'h0058;
    // Sweep interval1 reg
    parameter logic [15:0] A_SWEEP_INTERVAL1 = 16'h005C;
    // Sweep interval2 reg
    parameter logic [15:0] A_SWEEP_INTERVAL2 = 16'h0060;
    // Sweep interval3 reg
    parameter logic [15:0] A_SWEEP_INTERVAL3 = 16'h0064;
    // Sweep interval4 reg
    parameter logic [15:0] A_SWEEP_INTERVAL4 = 16'h0068;
    // Sweep interval5 reg
    parameter logic [15:0] A_SWEEP_INTERVAL5 = 16'h006C;
    // Sweep interval6 reg
    parameter logic [15:0] A_SWEEP_INTERVAL6 = 16'h0070;
    // Sweep interval7 reg
    parameter logic [15:0] A_SWEEP_INTERVAL7 = 16'h0074;
    // Sweep interval8 reg
    parameter logic [15:0] A_SWEEP_INTERVAL8 = 16'h0078;
    // Sweep interval9 reg
    parameter logic [15:0] A_SWEEP_INTERVAL9 = 16'h007C;
    // Sweep interval10 reg
    parameter logic [15:0] A_SWEEP_INTERVAL10 = 16'h0080;
    // Sweep interval11 reg
    parameter logic [15:0] A_SWEEP_INTERVAL11 = 16'h0084;
    // Sweep interval12 reg
    parameter logic [15:0] A_SWEEP_INTERVAL12 = 16'h0088;
    // Sweep interval13 reg
    parameter logic [15:0] A_SWEEP_INTERVAL13 = 16'h008C;
    // Sweep interval14 reg
    parameter logic [15:0] A_SWEEP_INTERVAL14 = 16'h0090;
    // Sweep interval15 reg
    parameter logic [15:0] A_SWEEP_INTERVAL15 = 16'h0094;
    // Sweep interval16 reg
    parameter logic [15:0] A_SWEEP_INTERVAL16 = 16'h0098;
    // Sweep interval17 reg
    parameter logic [15:0] A_SWEEP_INTERVAL17 = 16'h009C;
    // Sweep interval18 reg
    parameter logic [15:0] A_SWEEP_INTERVAL18 = 16'h00A0;
    // Sweep interval19 reg
    parameter logic [15:0] A_SWEEP_INTERVAL19 = 16'h00A4;
    // Sweep interval20 reg
    parameter logic [15:0] A_SWEEP_INTERVAL20 = 16'h00A8;
    // Sweep interval21 reg
    parameter logic [15:0] A_SWEEP_INTERVAL21 = 16'h00AC;
    // Sweep interval22 reg
    parameter logic [15:0] A_SWEEP_INTERVAL22 = 16'h00B0;
    // Sweep interval23 reg
    parameter logic [15:0] A_SWEEP_INTERVAL23 = 16'h00B4;
    // Sweep interval24 reg
    parameter logic [15:0] A_SWEEP_INTERVAL24 = 16'h00B8;
    // Sweep interval25 reg
    parameter logic [15:0] A_SWEEP_INTERVAL25 = 16'h00BC;
    // Sweep interval26 reg
    parameter logic [15:0] A_SWEEP_INTERVAL26 = 16'h00C0;
    // Sweep interval27 reg
    parameter logic [15:0] A_SWEEP_INTERVAL27 = 16'h00C4;
    // Sweep interval28 reg
    parameter logic [15:0] A_SWEEP_INTERVAL28 = 16'h00C8;
    // Sweep interval29 reg
    parameter logic [15:0] A_SWEEP_INTERVAL29 = 16'h00CC;
    // Sweep interval30 reg
    parameter logic [15:0] A_SWEEP_INTERVAL30 = 16'h00D0;
    // Sweep interval31 reg
    parameter logic [15:0] A_SWEEP_INTERVAL31 = 16'h00D4;
    parameter SWEEP_INTERVAL0_WIDTH = 16;
    parameter SWEEP_INTERVAL0_LSB = 0;
    parameter SWEEP_INTERVAL0_MSB = SWEEP_INTERVAL0_LSB + SWEEP_INTERVAL0_WIDTH - 1;
    parameter SWEEP_INTERVAL1_WIDTH = 16;
    parameter SWEEP_INTERVAL1_LSB = 16;
    parameter SWEEP_INTERVAL1_MSB = SWEEP_INTERVAL1_LSB + SWEEP_INTERVAL1_WIDTH - 1;
    parameter SWEEP_INTERVAL_PACKED_WIDTH = SWEEP_INTERVAL0_WIDTH + SWEEP_INTERVAL1_WIDTH;
    parameter SWEEP_INTERVAL0_PACKED_LSB = 0;
    parameter SWEEP_INTERVAL0_PACKED_MSB = SWEEP_INTERVAL0_PACKED_LSB + SWEEP_INTERVAL0_WIDTH - 1;
    parameter SWEEP_INTERVAL1_PACKED_LSB = SWEEP_INTERVAL0_PACKED_MSB + 1;
    parameter SWEEP_INTERVAL1_PACKED_MSB = SWEEP_INTERVAL1_PACKED_LSB + SWEEP_INTERVAL1_WIDTH - 1;

    // Global cfg reg
    parameter logic [15:0] A_GLOBAL_CFG = 16'h0004;
    parameter NUM_SWEEP_WIDTH = 24;
    parameter NUM_SWEEP_LSB = 0;
    parameter NUM_SWEEP_MSB = NUM_SWEEP_LSB + NUM_SWEEP_WIDTH - 1;
    parameter NUM_MAJORITY_WIDTH = $clog2(NUM_MAJORITY_MAX);
    parameter NUM_MAJORITY_LSB = 24;
    parameter NUM_MAJORITY_MSB = NUM_MAJORITY_LSB + NUM_MAJORITY_WIDTH - 1;

    parameter GLOBAL_CFG_PACKED_WIDTH = NUM_SWEEP_WIDTH + NUM_MAJORITY_WIDTH;
    parameter NUM_SWEEP_PACKED_LSB = 0;
    parameter NUM_SWEEP_PACKED_MSB = NUM_SWEEP_PACKED_LSB + NUM_SWEEP_WIDTH - 1;
    parameter NUM_MAJORITY_PACKED_LSB = NUM_SWEEP_PACKED_MSB + 1;
    parameter NUM_MAJORITY_PACKED_MSB = NUM_MAJORITY_PACKED_LSB + NUM_MAJORITY_WIDTH - 1;

    // Global ctrl reg
    parameter logic [15:0] A_GLOBAL_CTRL = 16'h0000;
    parameter SOFT_RESET_WIDTH = 1;
    parameter SOFT_RESET_LSB = 0;
    parameter SOFT_RESET_MSB = SOFT_RESET_LSB + SOFT_RESET_WIDTH - 1;
    parameter CFG_DONE_SET_WIDTH = 1;
    parameter CFG_DONE_SET_LSB = 1;
    parameter CFG_DONE_SET_MSB = CFG_DONE_SET_LSB + CFG_DONE_SET_WIDTH - 1;
    parameter CFG_DONE_CLEAR_WIDTH = 1;
    parameter CFG_DONE_CLEAR_LSB = 2;
    parameter CFG_DONE_CLEAR_MSB = CFG_DONE_CLEAR_LSB + CFG_DONE_CLEAR_WIDTH - 1;
    parameter RUN_START_WIDTH = 1;
    parameter RUN_START_LSB = 3;
    parameter RUN_START_MSB = RUN_START_LSB + RUN_START_WIDTH - 1;
    parameter SNAPSHOT_LATCH_WIDTH = 1;
    parameter SNAPSHOT_LATCH_LSB = 4;
    parameter SNAPSHOT_LATCH_MSB = SNAPSHOT_LATCH_LSB + SNAPSHOT_LATCH_WIDTH - 1;
    parameter RUN_DONE_CLEAR_WIDTH = 1;
    parameter RUN_DONE_CLEAR_LSB = 5;
    parameter RUN_DONE_CLEAR_MSB = RUN_DONE_CLEAR_LSB + RUN_DONE_CLEAR_WIDTH - 1;
    parameter ERROR_CLEAR_WIDTH = 1;
    parameter ERROR_CLEAR_LSB = 6;
    parameter ERROR_CLEAR_MSB = ERROR_CLEAR_LSB + ERROR_CLEAR_WIDTH - 1;

    parameter GLOBAL_CTRL_PACKED_WIDTH = SOFT_RESET_WIDTH + CFG_DONE_SET_WIDTH + CFG_DONE_CLEAR_WIDTH + RUN_START_WIDTH + SNAPSHOT_LATCH_WIDTH + RUN_DONE_CLEAR_WIDTH + ERROR_CLEAR_WIDTH;
    parameter SOFT_RESET_PACKED_LSB = 0;
    parameter SOFT_RESET_PACKED_MSB = SOFT_RESET_PACKED_LSB + SOFT_RESET_WIDTH - 1;
    parameter CFG_DONE_SET_PACKED_LSB = SOFT_RESET_PACKED_MSB + 1;
    parameter CFG_DONE_SET_PACKED_MSB = CFG_DONE_SET_PACKED_LSB + CFG_DONE_SET_WIDTH - 1;
    parameter CFG_DONE_CLEAR_PACKED_LSB = CFG_DONE_SET_PACKED_MSB + 1;
    parameter CFG_DONE_CLEAR_PACKED_MSB = CFG_DONE_CLEAR_PACKED_LSB + CFG_DONE_CLEAR_WIDTH - 1;
    parameter RUN_START_PACKED_LSB = CFG_DONE_CLEAR_PACKED_MSB + 1;
    parameter RUN_START_PACKED_MSB = RUN_START_PACKED_LSB + RUN_START_WIDTH - 1;
    parameter SNAPSHOT_LATCH_PACKED_LSB = RUN_START_PACKED_MSB + 1;
    parameter SNAPSHOT_LATCH_PACKED_MSB = SNAPSHOT_LATCH_PACKED_LSB + SNAPSHOT_LATCH_WIDTH - 1;
    parameter RUN_DONE_CLEAR_PACKED_LSB = SNAPSHOT_LATCH_PACKED_MSB + 1;
    parameter RUN_DONE_CLEAR_PACKED_MSB = RUN_DONE_CLEAR_PACKED_LSB + RUN_DONE_CLEAR_WIDTH - 1;
    parameter ERROR_CLEAR_PACKED_LSB = RUN_DONE_CLEAR_PACKED_MSB + 1;
    parameter ERROR_CLEAR_PACKED_MSB = ERROR_CLEAR_PACKED_LSB + ERROR_CLEAR_WIDTH - 1;

    // Node cmd reg
    parameter logic [15:0] A_NODE_CMD = 16'h00E4;
    parameter APPLY_CFG_WIDTH = 1;
    parameter APPLY_CFG_LSB = 0;
    parameter APPLY_CFG_MSB = APPLY_CFG_LSB + APPLY_CFG_WIDTH - 1;
    parameter APPLY_SEED_WIDTH = 1;
    parameter APPLY_SEED_LSB = 1;
    parameter APPLY_SEED_MSB = APPLY_SEED_LSB + APPLY_SEED_WIDTH - 1;    
    parameter LOAD_NODE_WIDTH = 1;
    parameter LOAD_NODE_LSB = 2;
    parameter LOAD_NODE_MSB = LOAD_NODE_LSB + LOAD_NODE_WIDTH - 1;
    parameter CLEAR_CFG_SCOPE_EN_WIDTH = 1;
    parameter CLEAR_CFG_SCOPE_EN_LSB = 3;
    parameter CLEAR_CFG_SCOPE_EN_MSB = CLEAR_CFG_SCOPE_EN_LSB + CLEAR_CFG_SCOPE_EN_WIDTH - 1;
    parameter CLEAR_SEED_SCOPE_EN_WIDTH = 1;
    parameter CLEAR_SEED_SCOPE_EN_LSB = 4;
    parameter CLEAR_SEED_SCOPE_EN_MSB = CLEAR_SEED_SCOPE_EN_LSB + CLEAR_SEED_SCOPE_EN_WIDTH - 1;
    parameter CLEAR_LOCAL_ALL_WIDTH = 1;
    parameter CLEAR_LOCAL_ALL_LSB = 5;
    parameter CLEAR_LOCAL_ALL_MSB = CLEAR_LOCAL_ALL_LSB + CLEAR_LOCAL_ALL_WIDTH - 1;
    parameter READBACK_CFG_WIDTH = 1;
    parameter READBACK_CFG_LSB = 6;
    parameter READBACK_CFG_MSB = READBACK_CFG_LSB + READBACK_CFG_WIDTH - 1;
    parameter READBACK_SEED_WIDTH = 1;
    parameter READBACK_SEED_LSB = 7;
    parameter READBACK_SEED_MSB = READBACK_SEED_LSB + READBACK_SEED_WIDTH - 1;

    parameter NODE_CMD_PACKED_WIDTH = APPLY_CFG_WIDTH + APPLY_SEED_WIDTH + LOAD_NODE_WIDTH + CLEAR_CFG_SCOPE_EN_WIDTH + CLEAR_SEED_SCOPE_EN_WIDTH + CLEAR_LOCAL_ALL_WIDTH + READBACK_CFG_WIDTH + READBACK_SEED_WIDTH;
    parameter APPLY_CFG_PACKED_LSB = 0;
    parameter APPLY_CFG_PACKED_MSB = APPLY_CFG_PACKED_LSB + APPLY_CFG_WIDTH - 1;
    parameter APPLY_SEED_PACKED_LSB = APPLY_CFG_PACKED_MSB + 1;
    parameter APPLY_SEED_PACKED_MSB = APPLY_SEED_PACKED_LSB + APPLY_SEED_WIDTH - 1;
    parameter LOAD_NODE_PACKED_LSB = APPLY_SEED_PACKED_MSB + 1;
    parameter LOAD_NODE_PACKED_MSB = LOAD_NODE_PACKED_LSB + LOAD_NODE_WIDTH - 1;
    parameter CLEAR_CFG_SCOPE_EN_PACKED_LSB = LOAD_NODE_PACKED_MSB + 1;
    parameter CLEAR_CFG_SCOPE_EN_PACKED_MSB = CLEAR_CFG_SCOPE_EN_PACKED_LSB + CLEAR_CFG_SCOPE_EN_WIDTH - 1;
    parameter CLEAR_SEED_SCOPE_EN_PACKED_LSB = CLEAR_CFG_SCOPE_EN_PACKED_MSB + 1;
    parameter CLEAR_SEED_SCOPE_EN_PACKED_MSB = CLEAR_SEED_SCOPE_EN_PACKED_LSB + CLEAR_SEED_SCOPE_EN_WIDTH - 1;
    parameter CLEAR_LOCAL_ALL_PACKED_LSB = CLEAR_SEED_SCOPE_EN_PACKED_MSB + 1;
    parameter CLEAR_LOCAL_ALL_PACKED_MSB = CLEAR_LOCAL_ALL_PACKED_LSB + CLEAR_LOCAL_ALL_WIDTH - 1;
    parameter READBACK_CFG_PACKED_LSB = CLEAR_LOCAL_ALL_PACKED_MSB + 1;
    parameter READBACK_CFG_PACKED_MSB = READBACK_CFG_PACKED_LSB + READBACK_CFG_WIDTH - 1;
    parameter READBACK_SEED_PACKED_LSB = READBACK_CFG_PACKED_MSB + 1;
    parameter READBACK_SEED_PACKED_MSB = READBACK_SEED_PACKED_LSB + READBACK_SEED_WIDTH - 1;

    // Edge cmd reg
    parameter logic [15:0] A_EDGE_CMD = 16'h00F8;
    parameter APPLY_EDGE_WIDTH = 1;
    parameter APPLY_EDGE_LSB = 0;
    parameter APPLY_EDGE_MSB = APPLY_EDGE_LSB + APPLY_EDGE_WIDTH - 1;
    parameter CLEAR_EDGE_WIDTH = 1;
    parameter CLEAR_EDGE_LSB = 1;
    parameter CLEAR_EDGE_MSB = CLEAR_EDGE_LSB + CLEAR_EDGE_WIDTH - 1;
    parameter READBACK_EDGE_WIDTH = 1;
    parameter READBACK_EDGE_LSB = 2;
    parameter READBACK_EDGE_MSB = READBACK_EDGE_LSB + READBACK_EDGE_WIDTH - 1;

    parameter EDGE_CMD_PACKED_WIDTH = APPLY_EDGE_WIDTH + CLEAR_EDGE_WIDTH + READBACK_EDGE_WIDTH;
    parameter APPLY_EDGE_PACKED_LSB = 0;
    parameter APPLY_EDGE_PACKED_MSB = APPLY_EDGE_PACKED_LSB + APPLY_EDGE_WIDTH - 1;
    parameter CLEAR_EDGE_PACKED_LSB = APPLY_EDGE_PACKED_MSB + 1;
    parameter CLEAR_EDGE_PACKED_MSB = CLEAR_EDGE_PACKED_LSB + CLEAR_EDGE_WIDTH - 1;
    parameter READBACK_EDGE_PACKED_LSB = CLEAR_EDGE_PACKED_MSB + 1;
    parameter READBACK_EDGE_PACKED_MSB = READBACK_EDGE_PACKED_LSB + READBACK_EDGE_WIDTH - 1;

 // Global status reg
    parameter logic [15:0] A_GLOBAL_STATUS = 16'h0008;
    parameter CFG_DONE_WIDTH = 1;
    parameter CFG_DONE_LSB = 0;
    parameter CFG_DONE_MSB = CFG_DONE_LSB + CFG_DONE_WIDTH - 1;
    parameter RUN_BUSY_WIDTH = 1;
    parameter RUN_BUSY_LSB = 1;
    parameter RUN_BUSY_MSB = RUN_BUSY_LSB + RUN_BUSY_WIDTH - 1;
    parameter RUN_DONE_WIDTH = 1;
    parameter RUN_DONE_LSB = 2;
    parameter RUN_DONE_MSB = RUN_DONE_LSB + RUN_DONE_WIDTH - 1;
    parameter NODE_CMD_DONE_WIDTH = 1;
    parameter NODE_CMD_DONE_LSB = 3;
    parameter NODE_CMD_DONE_MSB = NODE_CMD_DONE_LSB + NODE_CMD_DONE_WIDTH - 1;
    parameter EDGE_CMD_DONE_WIDTH = 1;
    parameter EDGE_CMD_DONE_LSB = 4;
    parameter EDGE_CMD_DONE_MSB = EDGE_CMD_DONE_LSB + EDGE_CMD_DONE_WIDTH - 1;
    parameter SNAPSHOT_VALID_WIDTH = 1;
    parameter SNAPSHOT_VALID_LSB = 5;
    parameter SNAPSHOT_VALID_MSB = SNAPSHOT_VALID_LSB + SNAPSHOT_VALID_WIDTH - 1;
    parameter ERROR_WIDTH = 1;
    parameter ERROR_LSB = 6;
    parameter ERROR_MSB = ERROR_LSB + ERROR_WIDTH - 1;

    parameter GLOBAL_STATUS_PACKED_WIDTH = CFG_DONE_WIDTH + RUN_BUSY_WIDTH + RUN_DONE_WIDTH + NODE_CMD_DONE_WIDTH + EDGE_CMD_DONE_WIDTH + SNAPSHOT_VALID_WIDTH + ERROR_WIDTH;
    parameter CFG_DONE_PACKED_LSB = 0;
    parameter CFG_DONE_PACKED_MSB = CFG_DONE_PACKED_LSB + CFG_DONE_WIDTH - 1;
    parameter RUN_BUSY_PACKED_LSB = CFG_DONE_PACKED_MSB + 1;
    parameter RUN_BUSY_PACKED_MSB = RUN_BUSY_PACKED_LSB + RUN_BUSY_WIDTH - 1;
    parameter RUN_DONE_PACKED_LSB = RUN_BUSY_PACKED_MSB + 1;
    parameter RUN_DONE_PACKED_MSB = RUN_DONE_PACKED_LSB + RUN_DONE_WIDTH - 1;
    parameter NODE_CMD_DONE_PACKED_LSB = RUN_DONE_PACKED_MSB + 1;
    parameter NODE_CMD_DONE_PACKED_MSB = NODE_CMD_DONE_PACKED_LSB + NODE_CMD_DONE_WIDTH - 1;
    parameter EDGE_CMD_DONE_PACKED_LSB = NODE_CMD_DONE_PACKED_MSB + 1;
    parameter EDGE_CMD_DONE_PACKED_MSB = EDGE_CMD_DONE_PACKED_LSB + EDGE_CMD_DONE_WIDTH - 1;
    parameter SNAPSHOT_VALID_PACKED_LSB = EDGE_CMD_DONE_PACKED_MSB + 1;
    parameter SNAPSHOT_VALID_PACKED_MSB = SNAPSHOT_VALID_PACKED_LSB + SNAPSHOT_VALID_WIDTH - 1;
    parameter ERROR_PACKED_LSB = SNAPSHOT_VALID_PACKED_MSB + 1;
    parameter ERROR_PACKED_MSB = ERROR_PACKED_LSB + ERROR_WIDTH - 1;

    // Array param reg
    parameter logic [15:0] A_ARRAY_PARAM = 16'h000C;
    parameter ROWS_WIDTH = 8;
    parameter ROWS_LSB = 0;
    parameter ROWS_MSB = ROWS_LSB + ROWS_WIDTH - 1;
    parameter COLS_WIDTH = 8;
    parameter COLS_LSB = 8;
    parameter COLS_MSB = COLS_LSB + COLS_WIDTH - 1;
    parameter N_SPIN_WIDTH = 16;
    parameter N_SPIN_LSB = 16;
    parameter N_SPIN_MSB = N_SPIN_LSB + N_SPIN_WIDTH - 1;

    parameter ARRAY_PARAM_PACKED_WIDTH = ROWS_WIDTH + COLS_WIDTH + N_SPIN_WIDTH;
    parameter ROWS_PACKED_LSB = 0;
    parameter ROWS_PACKED_MSB = ROWS_PACKED_LSB + ROWS_WIDTH - 1;
    parameter COLS_PACKED_LSB = ROWS_PACKED_MSB + 1;
    parameter COLS_PACKED_MSB = COLS_PACKED_LSB + COLS_WIDTH - 1;
    parameter N_SPIN_PACKED_LSB = COLS_PACKED_MSB + 1;
    parameter N_SPIN_PACKED_MSB = N_SPIN_PACKED_LSB + N_SPIN_WIDTH - 1;

    // Error status reg
    parameter logic [16:0] A_ERROR_STATUS = 17'h0010;
    parameter ADDR_ERR_WIDTH = 1;
    parameter ADDR_ERR_LSB = 0;
    parameter ADDR_ERR_MSB = ADDR_ERR_LSB + ADDR_ERR_WIDTH - 1;
    parameter WR_TO_RO_WIDTH = 1;
    parameter WR_TO_RO_LSB = 1;
    parameter WR_TO_RO_MSB = WR_TO_RO_LSB + WR_TO_RO_WIDTH - 1;
    parameter RD_TO_WO_WIDTH = 1;
    parameter RD_TO_WO_LSB = 2;
    parameter RD_TO_WO_MSB = RD_TO_WO_LSB + RD_TO_WO_WIDTH - 1;
    parameter NODE_CFG_WHILE_RUN_WIDTH = 1;
    parameter NODE_CFG_WHILE_RUN_LSB = 3;
    parameter NODE_CFG_WHILE_RUN_MSB = NODE_CFG_WHILE_RUN_LSB + NODE_CFG_WHILE_RUN_WIDTH - 1;
    parameter EDGE_CFG_WHILE_RUN_WIDTH = 1;
    parameter EDGE_CFG_WHILE_RUN_LSB = 4;
    parameter EDGE_CFG_WHILE_RUN_MSB = EDGE_CFG_WHILE_RUN_LSB + EDGE_CFG_WHILE_RUN_WIDTH - 1;
    parameter RUN_WITHOUT_CFG_DONE_WIDTH = 1;
    parameter RUN_WITHOUT_CFG_DONE_LSB = 5;
    parameter RUN_WITHOUT_CFG_DONE_MSB = RUN_WITHOUT_CFG_DONE_LSB + RUN_WITHOUT_CFG_DONE_WIDTH - 1;
    parameter RUN_WHEN_BUSY_WIDTH = 1;
    parameter RUN_WHEN_BUSY_LSB = 6;
    parameter RUN_WHEN_BUSY_MSB = RUN_WHEN_BUSY_LSB + RUN_WHEN_BUSY_WIDTH - 1;
    parameter NODE_TARGET_MODE_ERR_WIDTH = 1;
    parameter NODE_TARGET_MODE_ERR_LSB = 7;
    parameter NODE_TARGET_MODE_ERR_MSB = NODE_TARGET_MODE_ERR_LSB + NODE_TARGET_MODE_ERR_WIDTH - 1;
    parameter NODE_ROW_OOR_WIDTH = 1;
    parameter NODE_ROW_OOR_LSB = 8;
    parameter NODE_ROW_OOR_MSB = NODE_ROW_OOR_LSB + NODE_ROW_OOR_WIDTH - 1;
    parameter NODE_COL_OOR_WIDTH = 1;
    parameter NODE_COL_OOR_LSB = 9;
    parameter NODE_COL_OOR_MSB = NODE_COL_OOR_LSB + NODE_COL_OOR_WIDTH - 1;
    parameter SEED_ROW_OOR_WIDTH = 1;
    parameter SEED_ROW_OOR_LSB = 10;
    parameter SEED_ROW_OOR_MSB = SEED_ROW_OOR_LSB + SEED_ROW_OOR_WIDTH - 1;
    parameter SEED_COL_OOR_WIDTH = 1;
    parameter SEED_COL_OOR_LSB = 11;
    parameter SEED_COL_OOR_MSB = SEED_COL_OOR_LSB + SEED_COL_OOR_WIDTH - 1;
    parameter EDGE_ROW_OOR_WIDTH = 1;
    parameter EDGE_ROW_OOR_LSB = 12;
    parameter EDGE_ROW_OOR_MSB = EDGE_ROW_OOR_LSB + EDGE_ROW_OOR_WIDTH - 1;
    parameter EDGE_COL_OOR_WIDTH = 1;
    parameter EDGE_COL_OOR_LSB = 13;
    parameter EDGE_COL_OOR_MSB = EDGE_COL_OOR_LSB + EDGE_COL_OOR_WIDTH - 1;
    parameter EDGE_TYPE_ERR_WIDTH = 1;
    parameter EDGE_TYPE_ERR_LSB = 14;
    parameter EDGE_TYPE_ERR_MSB = EDGE_TYPE_ERR_LSB + EDGE_TYPE_ERR_WIDTH - 1;
    parameter UART_FRAME_ERR_WIDTH = 1;
    parameter UART_FRAME_ERR_LSB = 15;
    parameter UART_FRAME_ERR_MSB = UART_FRAME_ERR_LSB + UART_FRAME_ERR_WIDTH - 1;
    parameter UART_OVERFLOW_WIDTH = 1;
    parameter UART_OVERFLOW_LSB = 16;
    parameter UART_OVERFLOW_MSB = UART_OVERFLOW_LSB + UART_OVERFLOW_WIDTH - 1;
    parameter SNAP_ADDR_OOR_WIDTH = 1;
    parameter SNAP_ADDR_OOR_LSB = 17;
    parameter SNAP_ADDR_OOR_MSB = SNAP_ADDR_OOR_LSB + SNAP_ADDR_OOR_WIDTH - 1;

    parameter ERROR_STATUS_PACKED_WIDTH = ADDR_ERR_WIDTH + WR_TO_RO_WIDTH + RD_TO_WO_WIDTH + NODE_CFG_WHILE_RUN_WIDTH + EDGE_CFG_WHILE_RUN_WIDTH + RUN_WITHOUT_CFG_DONE_WIDTH + RUN_WHEN_BUSY_WIDTH + NODE_TARGET_MODE_ERR_WIDTH + NODE_ROW_OOR_WIDTH + NODE_COL_OOR_WIDTH + SEED_ROW_OOR_WIDTH + SEED_COL_OOR_WIDTH + EDGE_ROW_OOR_WIDTH + EDGE_COL_OOR_WIDTH + EDGE_TYPE_ERR_WIDTH + UART_FRAME_ERR_WIDTH + UART_OVERFLOW_WIDTH + SNAP_ADDR_OOR_WIDTH;
    parameter ADDR_ERR_PACKED_LSB = 0;
    parameter ADDR_ERR_PACKED_MSB = ADDR_ERR_PACKED_LSB + ADDR_ERR_WIDTH - 1;
    parameter WR_TO_RO_PACKED_LSB = ADDR_ERR_PACKED_MSB + 1;
    parameter WR_TO_RO_PACKED_MSB = WR_TO_RO_PACKED_LSB + WR_TO_RO_WIDTH - 1;
    parameter RD_TO_WO_PACKED_LSB = WR_TO_RO_PACKED_MSB + 1;
    parameter RD_TO_WO_PACKED_MSB = RD_TO_WO_PACKED_LSB + RD_TO_WO_WIDTH - 1;
    parameter NODE_CFG_WHILE_RUN_PACKED_LSB = RD_TO_WO_PACKED_MSB + 1;
    parameter NODE_CFG_WHILE_RUN_PACKED_MSB = NODE_CFG_WHILE_RUN_PACKED_LSB + NODE_CFG_WHILE_RUN_WIDTH - 1;
    parameter EDGE_CFG_WHILE_RUN_PACKED_LSB = NODE_CFG_WHILE_RUN_PACKED_MSB + 1;
    parameter EDGE_CFG_WHILE_RUN_PACKED_MSB = EDGE_CFG_WHILE_RUN_PACKED_LSB + EDGE_CFG_WHILE_RUN_WIDTH - 1;
    parameter RUN_WITHOUT_CFG_DONE_PACKED_LSB = EDGE_CFG_WHILE_RUN_PACKED_MSB + 1;
    parameter RUN_WITHOUT_CFG_DONE_PACKED_MSB = RUN_WITHOUT_CFG_DONE_PACKED_LSB + RUN_WITHOUT_CFG_DONE_WIDTH - 1;
    parameter RUN_WHEN_BUSY_PACKED_LSB = RUN_WITHOUT_CFG_DONE_PACKED_MSB + 1;
    parameter RUN_WHEN_BUSY_PACKED_MSB = RUN_WHEN_BUSY_PACKED_LSB + RUN_WHEN_BUSY_WIDTH - 1;
    parameter NODE_TARGET_MODE_ERR_PACKED_LSB = RUN_WHEN_BUSY_PACKED_MSB + 1;
    parameter NODE_TARGET_MODE_ERR_PACKED_MSB = NODE_TARGET_MODE_ERR_PACKED_LSB + NODE_TARGET_MODE_ERR_WIDTH - 1;
    parameter NODE_ROW_OOR_PACKED_LSB = NODE_TARGET_MODE_ERR_PACKED_MSB + 1;
    parameter NODE_ROW_OOR_PACKED_MSB = NODE_ROW_OOR_PACKED_LSB + NODE_ROW_OOR_WIDTH - 1;
    parameter NODE_COL_OOR_PACKED_LSB = NODE_ROW_OOR_PACKED_MSB + 1;
    parameter NODE_COL_OOR_PACKED_MSB = NODE_COL_OOR_PACKED_LSB + NODE_COL_OOR_WIDTH - 1;
    parameter SEED_ROW_OOR_PACKED_LSB = NODE_COL_OOR_PACKED_MSB + 1;
    parameter SEED_ROW_OOR_PACKED_MSB = SEED_ROW_OOR_PACKED_LSB + SEED_ROW_OOR_WIDTH - 1;
    parameter SEED_COL_OOR_PACKED_LSB = SEED_ROW_OOR_PACKED_MSB + 1;
    parameter SEED_COL_OOR_PACKED_MSB = SEED_COL_OOR_PACKED_LSB + SEED_COL_OOR_WIDTH - 1;
    parameter EDGE_ROW_OOR_PACKED_LSB = SEED_COL_OOR_PACKED_MSB + 1;
    parameter EDGE_ROW_OOR_PACKED_MSB = EDGE_ROW_OOR_PACKED_LSB + EDGE_ROW_OOR_WIDTH - 1;
    parameter EDGE_COL_OOR_PACKED_LSB = EDGE_ROW_OOR_PACKED_MSB + 1;
    parameter EDGE_COL_OOR_PACKED_MSB = EDGE_COL_OOR_PACKED_LSB + EDGE_COL_OOR_WIDTH - 1;
    parameter EDGE_TYPE_ERR_PACKED_LSB = EDGE_COL_OOR_PACKED_MSB + 1;
    parameter EDGE_TYPE_ERR_PACKED_MSB = EDGE_TYPE_ERR_PACKED_LSB + EDGE_TYPE_ERR_WIDTH - 1;
    parameter UART_FRAME_ERR_PACKED_LSB = EDGE_TYPE_ERR_PACKED_MSB + 1;
    parameter UART_FRAME_ERR_PACKED_MSB = UART_FRAME_ERR_PACKED_LSB + UART_FRAME_ERR_WIDTH - 1;
    parameter UART_OVERFLOW_PACKED_LSB = UART_FRAME_ERR_PACKED_MSB + 1;
    parameter UART_OVERFLOW_PACKED_MSB = UART_OVERFLOW_PACKED_LSB + UART_OVERFLOW_WIDTH - 1;
    parameter SNAP_ADDR_OOR_PACKED_LSB = UART_OVERFLOW_PACKED_MSB + 1;
    parameter SNAP_ADDR_OOR_PACKED_MSB = SNAP_ADDR_OOR_PACKED_LSB + SNAP_ADDR_OOR_WIDTH - 1;

    // Node rdata cfg reg
    parameter logic [15:0] A_NODE_RDATA_CFG = 16'h00E8;
    parameter NODE_RDATA_CFG_INIT_SPIN_WIDTH = 1;
    parameter NODE_RDATA_CFG_INIT_SPIN_LSB = 0;
    parameter NODE_RDATA_CFG_INIT_SPIN_MSB = NODE_RDATA_CFG_INIT_SPIN_LSB + NODE_RDATA_CFG_INIT_SPIN_WIDTH - 1;
    parameter NODE_RDATA_CFG_CLAMP_EN_WIDTH = 1;
    parameter NODE_RDATA_CFG_CLAMP_EN_LSB = 1;
    parameter NODE_RDATA_CFG_CLAMP_EN_MSB = NODE_RDATA_CFG_CLAMP_EN_LSB + NODE_RDATA_CFG_CLAMP_EN_WIDTH - 1;
    parameter NODE_RDATA_CFG_CLAMP_SPIN_WIDTH = 1;
    parameter NODE_RDATA_CFG_CLAMP_SPIN_LSB = 2;
    parameter NODE_RDATA_CFG_CLAMP_SPIN_MSB = NODE_RDATA_CFG_CLAMP_SPIN_LSB + NODE_RDATA_CFG_CLAMP_SPIN_WIDTH - 1;
    parameter NODE_RDATA_CFG_BIAS_SIGN_WIDTH = 1;
    parameter NODE_RDATA_CFG_BIAS_SIGN_LSB = 3;
    parameter NODE_RDATA_CFG_BIAS_SIGN_MSB = NODE_RDATA_CFG_BIAS_SIGN_LSB + NODE_RDATA_CFG_BIAS_SIGN_WIDTH - 1;
    parameter NODE_RDATA_CFG_BIAS_PROB_WIDTH = 7;
    parameter NODE_RDATA_CFG_BIAS_PROB_LSB = 4;
    parameter NODE_RDATA_CFG_BIAS_PROB_MSB = NODE_RDATA_CFG_BIAS_PROB_LSB + NODE_RDATA_CFG_BIAS_PROB_WIDTH - 1;

    parameter NODE_RDATA_CFG_PACKED_WIDTH = NODE_RDATA_CFG_INIT_SPIN_WIDTH + NODE_RDATA_CFG_CLAMP_EN_WIDTH + NODE_RDATA_CFG_CLAMP_SPIN_WIDTH + NODE_RDATA_CFG_BIAS_SIGN_WIDTH + NODE_RDATA_CFG_BIAS_PROB_WIDTH;
    parameter NODE_RDATA_CFG_INIT_SPIN_PACKED_LSB = 0;
    parameter NODE_RDATA_CFG_INIT_SPIN_PACKED_MSB = NODE_RDATA_CFG_INIT_SPIN_PACKED_LSB + NODE_RDATA_CFG_INIT_SPIN_WIDTH - 1;
    parameter NODE_RDATA_CFG_CLAMP_EN_PACKED_LSB = NODE_RDATA_CFG_INIT_SPIN_PACKED_MSB + 1;
    parameter NODE_RDATA_CFG_CLAMP_EN_PACKED_MSB = NODE_RDATA_CFG_CLAMP_EN_PACKED_LSB + NODE_RDATA_CFG_CLAMP_EN_WIDTH - 1;
    parameter NODE_RDATA_CFG_CLAMP_SPIN_PACKED_LSB = NODE_RDATA_CFG_CLAMP_EN_PACKED_MSB + 1;
    parameter NODE_RDATA_CFG_CLAMP_SPIN_PACKED_MSB = NODE_RDATA_CFG_CLAMP_SPIN_PACKED_LSB + NODE_RDATA_CFG_CLAMP_SPIN_WIDTH - 1;
    parameter NODE_RDATA_CFG_BIAS_SIGN_PACKED_LSB = NODE_RDATA_CFG_CLAMP_SPIN_PACKED_MSB + 1;
    parameter NODE_RDATA_CFG_BIAS_SIGN_PACKED_MSB = NODE_RDATA_CFG_BIAS_SIGN_PACKED_LSB + NODE_RDATA_CFG_BIAS_SIGN_WIDTH - 1;
    parameter NODE_RDATA_CFG_BIAS_PROB_PACKED_LSB = NODE_RDATA_CFG_BIAS_SIGN_PACKED_MSB + 1;
    parameter NODE_RDATA_CFG_BIAS_PROB_PACKED_MSB = NODE_RDATA_CFG_BIAS_PROB_PACKED_LSB + NODE_RDATA_CFG_BIAS_PROB_WIDTH - 1;

    // Node rdaTa seed reg
    parameter logic [15:0] A_NODE_RDATA_SEED = 16'h00EC;
    parameter NODE_RDATA_SEED_WIDTH = 32;
    parameter NODE_RDATA_SEED_LSB = 0;
    parameter NODE_RDATA_SEED_MSB = NODE_RDATA_SEED_LSB + NODE_RDATA_SEED_WIDTH - 1;

    parameter NODE_RDATA_SEED_PACKED_WIDTH = NODE_RDATA_SEED_WIDTH;
    parameter NODE_RDATA_SEED_PACKED_LSB = 0;
    parameter NODE_RDATA_SEED_PACKED_MSB = NODE_RDATA_SEED_PACKED_LSB + NODE_RDATA_SEED_WIDTH - 1;

    // Edge rdata reg
    parameter logic [15:0] A_EDGE_RDATA = 16'h00FC;
    parameter EDGE_RDATA_EDGE_VALID_WIDTH = 1;
    parameter EDGE_RDATA_EDGE_VALID_LSB = 0;
    parameter EDGE_RDATA_EDGE_VALID_MSB = EDGE_RDATA_EDGE_VALID_LSB + EDGE_RDATA_EDGE_VALID_WIDTH - 1;
    parameter EDGE_RDATA_EDGE_SIGN_WIDTH = 1;
    parameter EDGE_RDATA_EDGE_SIGN_LSB = 1;
    parameter EDGE_RDATA_EDGE_SIGN_MSB = EDGE_RDATA_EDGE_SIGN_LSB + EDGE_RDATA_EDGE_SIGN_WIDTH - 1;
    parameter EDGE_RDATA_EDGE_PROB_WIDTH = 7;
    parameter EDGE_RDATA_EDGE_PROB_LSB = 2;
    parameter EDGE_RDATA_EDGE_PROB_MSB = EDGE_RDATA_EDGE_PROB_LSB + EDGE_RDATA_EDGE_PROB_WIDTH - 1;

    parameter EDGE_RDATA_PACKED_WIDTH = EDGE_RDATA_EDGE_VALID_WIDTH + EDGE_RDATA_EDGE_SIGN_WIDTH + EDGE_RDATA_EDGE_PROB_WIDTH;
    parameter EDGE_RDATA_EDGE_VALID_PACKED_LSB = 0;
    parameter EDGE_RDATA_EDGE_VALID_PACKED_MSB = EDGE_RDATA_EDGE_VALID_PACKED_LSB + EDGE_RDATA_EDGE_VALID_WIDTH - 1;
    parameter EDGE_RDATA_EDGE_SIGN_PACKED_LSB = EDGE_RDATA_EDGE_VALID_PACKED_MSB + 1;
    parameter EDGE_RDATA_EDGE_SIGN_PACKED_MSB = EDGE_RDATA_EDGE_SIGN_PACKED_LSB + EDGE_RDATA_EDGE_SIGN_WIDTH - 1;
    parameter EDGE_RDATA_EDGE_PROB_PACKED_LSB = EDGE_RDATA_EDGE_SIGN_PACKED_MSB + 1;
    parameter EDGE_RDATA_EDGE_PROB_PACKED_MSB = EDGE_RDATA_EDGE_PROB_PACKED_LSB + EDGE_RDATA_EDGE_PROB_WIDTH - 1;

 // Spin data0 reg
    parameter logic [15:0] A_SPIN_RDATA0 = 16'h0100;
    parameter SPIN_RDATA_DATA_WIDTH = 32;
    parameter SPIN_RDATA_DATA_LSB = 0;
    parameter SPIN_RDATA_DATA_MSB = SPIN_RDATA_DATA_LSB + SPIN_RDATA_DATA_WIDTH - 1;

    parameter SPIN_RDATA_PACKED_WIDTH = SPIN_RDATA_DATA_WIDTH;
    parameter SPIN_RDATA_DATA_PACKED_LSB = 0;
    parameter SPIN_RDATA_DATA_PACKED_MSB = SPIN_RDATA_DATA_PACKED_LSB + SPIN_RDATA_DATA_WIDTH - 1;

    // Spin data1 reg
    parameter logic [15:0] A_SPIN_RDATA1 = 16'h0104;

    // Spin data2 reg
    parameter logic [15:0] A_SPIN_RDATA2 = 16'h0108;

    // Spin data3 reg
    parameter logic [15:0] A_SPIN_RDATA3 = 16'h010C;

    // Spin data4 reg
    parameter logic [15:0] A_SPIN_RDATA4 = 16'h0110;

    // Spin data5 reg
    parameter logic [15:0] A_SPIN_RDATA5 = 16'h0114;

    // Spin data6 reg
    parameter logic [15:0] A_SPIN_RDATA6 = 16'h0118;

    // Spin data7 reg
    parameter logic [15:0] A_SPIN_RDATA7 = 16'h011C;

    // Spin data8 reg
    parameter logic [15:0] A_SPIN_RDATA8 = 16'h0120;

    // Spin data9 reg
    parameter logic [15:0] A_SPIN_RDATA9 = 16'h0124;
endpackage
`endif
